var Name = [
    "李佳歡-不痛",
    "閻奕格-也可以",
    "楊丞琳-青春住了誰",
    "林宥嘉-成全",
    "莫文蔚-慢慢喜歡你",
    "張韶涵-淋雨一直走",
    "周杰倫-夜曲",
    "梁文音-和平分手",
    "梁靜茹-情歌",
    "鄧紫棋-盲點",
    "林俊傑-修練愛情",
    "五月天-OAOA",
    "A-Lin-有一種悲傷",
    "李友廷-誰",
    "周興哲-怎麼了",
    "F.I.R-自由之歌",
    "李佳歡-崇拜",
    "王心凌-當你",
    "周杰倫-不愛我就拉倒",
    "盧廣仲-幾分之幾"
];
var musicFile = [
    "Guess_song/music/李佳歡 Kar Fun - 不痛(官方歌詞版).mp3",
    "Guess_song/music/閻奕格 Janice Yan [ 也可以 Might as well ] Official Music Video (電影「追婚日記」插曲).mp3",
    "Guess_song/music/楊丞琳Rainie Yang 青春住了誰Youth Lies Within(Official HD MV).mp3",
    "Guess_song/music/林宥嘉Yoga Lin[成全 Step aside]Official Live.mp3",
    "Guess_song/music/莫文蔚 慢慢喜歡你 歌詞.mp3",
    "Guess_song/music/張韶涵 淋雨一直走 歌詞.mp3",
    "Guess_song/music/周杰倫-夜曲(有字幕).mp3",
    "Guess_song/music/梁文音 Wen Yin Liang《和平分手》feat. 蕭煌奇 Ricky Hsiao - Official Music Video.mp3",
    "Guess_song/music/梁靜茹-情歌 MV(字幕清晰版).mp3",
    "Guess_song/music/G.E.M.【盲點 BLINDSPOT 】Official MV [HD] 鄧紫棋.mp3",
    "Guess_song/music/修煉愛情(歌詞).mp3",
    "Guess_song/music/Mayday五月天【OAOA(現在就是永遠)】MV官方完整版-[追夢3DNA]電影主題曲.mp3",
    "Guess_song/music/A-Lin《有一種悲傷 A Kind of Sorrow》Official Music Video - 電影『比悲傷更悲傷的故事』主題曲.mp3",
    "Guess_song/music/李友廷 yoLee《 誰 》Lyric Video.mp3",
    "Guess_song/music/Eric周興哲《怎麼了 Whats Wrong》Official Music Video - 華劇【你有念大學嗎？】片尾曲.mp3",
    "Guess_song/music/F.I.R. 飛兒樂團 末日青春二部曲 [ 自由之歌 The Freedom Song ] Official Music Video.mp3",
    "Guess_song/music/李佳歡Kar Fun - 崇拜(官方歌詞版).mp3",
    "Guess_song/music/當你 王心凌 (歌詞lyrics ).mp3",
    "Guess_song/music/周杰倫 不愛我就拉倒 歌詞.mp3",
    "Guess_song/music/盧廣仲 Crowd Lu 【幾分之幾 You Complete Me】 Official Music Video （花甲大人轉男孩電影主題曲）.mp3"
];